package com.muttaqi.shared.feature.quran

/** A few surahs as the Quran API gives them, word for word, for the tests */
internal object QuranTestData {
    data class AyahText(
        val surah: Int, val number: Int, val numberInSurah: Int, val juz: Int, val page: Int, val hizbQuarter: Int,
        val arabic: String, val transliteration: String, val english: String, val urdu: String,
    )
    data class SurahInfo(val number: Int, val name: String, val englishName: String, val englishNameTranslation: String, val revelationType: String, val numberOfAyahs: Int)

    val surahs = listOf(
        SurahInfo(1, "سورة الفاتحة", "Al-Faatiha", "The Opening", "Meccan", 7),
        SurahInfo(2, "سورة البقرة", "Al-Baqara", "The Cow", "Medinan", 286),
        SurahInfo(9, "سورة التوبة", "At-Tawba", "The Repentance", "Medinan", 129),
        SurahInfo(18, "سورة الكهف", "Al-Kahf", "The Cave", "Meccan", 110),
        SurahInfo(114, "سورة الناس", "An-Naas", "Mankind", "Meccan", 6),
    )

    val ayahs = listOf(
        AyahText(1, 1, 1, 1, 1, 1,
            "﻿بِسْمِ ٱللَّهِ ٱلرَّحْمَٰنِ ٱلرَّحِيمِ",
            "Bismillaahir Rahmaanir Raheem",
            "In the name of Allah, the Entirely Merciful, the Especially Merciful.",
            "شروع الله کا نام لے کر جو بڑا مہربان نہایت رحم والا ہے"),
        AyahText(1, 2, 2, 1, 1, 1,
            "ٱلْحَمْدُ لِلَّهِ رَبِّ ٱلْعَٰلَمِينَ",
            "Alhamdu lillaahi Rabbil 'aalameen",
            "[All] praise is [due] to Allah, Lord of the worlds -",
            "سب طرح کی تعریف خدا ہی کو (سزاوار) ہے جو تمام مخلوقات کا پروردگار ہے"),
        AyahText(1, 3, 3, 1, 1, 1,
            "ٱلرَّحْمَٰنِ ٱلرَّحِيمِ",
            "Ar-Rahmaanir-Raheem",
            "The Entirely Merciful, the Especially Merciful,",
            "بڑا مہربان نہایت رحم والا"),
        AyahText(1, 4, 4, 1, 1, 1,
            "مَٰلِكِ يَوْمِ ٱلدِّينِ",
            "Maaliki Yawmid-Deen",
            "Sovereign of the Day of Recompense.",
            "انصاف کے دن کا حاکم"),
        AyahText(1, 5, 5, 1, 1, 1,
            "إِيَّاكَ نَعْبُدُ وَإِيَّاكَ نَسْتَعِينُ",
            "Iyyaaka na'budu wa lyyaaka nasta'een",
            "It is You we worship and You we ask for help.",
            "(اے پروردگار) ہم تیری ہی عبادت کرتے ہیں اور تجھ ہی سے مدد مانگتے ہیں"),
        AyahText(1, 6, 6, 1, 1, 1,
            "ٱهْدِنَا ٱلصِّرَٰطَ ٱلْمُسْتَقِيمَ",
            "Ihdinas-Siraatal-Mustaqeem",
            "Guide us to the straight path -",
            "ہم کو سیدھے رستے چلا"),
        AyahText(1, 7, 7, 1, 1, 1,
            "صِرَٰطَ ٱلَّذِينَ أَنْعَمْتَ عَلَيْهِمْ غَيْرِ ٱلْمَغْضُوبِ عَلَيْهِمْ وَلَا ٱلضَّآلِّينَ",
            "Siraatal-lazeena an'amta 'alaihim ghayril-maghdoobi 'alaihim wa lad-daaalleen",
            "The path of those upon whom You have bestowed favor, not of those who have evoked [Your] anger or of those who are astray.",
            "ان لوگوں کے رستے جن پر تو اپنا فضل وکرم کرتا رہا نہ ان کے جن پر غصے ہوتا رہا اور نہ گمراہوں کے"),
        AyahText(2, 8, 1, 1, 2, 1,
            "الٓمٓ",
            "Alif-Laaam-Meeem",
            "Alif, Lam, Meem.",
            "الم"),
        AyahText(2, 9, 2, 1, 2, 1,
            "ذَٰلِكَ ٱلْكِتَٰبُ لَا رَيْبَ ۛ فِيهِ ۛ هُدًۭى لِّلْمُتَّقِينَ",
            "Zaalikal Kitaabu laa raiba feeh; udal lilmuttaqeen",
            "This is the Book about which there is no doubt, a guidance for those conscious of Allah -",
            "یہ کتاب (قرآن مجید) اس میں کچھ شک نہیں (کہ کلامِ خدا ہے۔ خدا سے) ڈرنے والوں کی رہنما ہے"),
        AyahText(2, 10, 3, 1, 2, 1,
            "ٱلَّذِينَ يُؤْمِنُونَ بِٱلْغَيْبِ وَيُقِيمُونَ ٱلصَّلَوٰةَ وَمِمَّا رَزَقْنَٰهُمْ يُنفِقُونَ",
            "Allazeena yu'minoona bilghaibi wa yuqeemoonas salaata wa mimmaa razaqnaahum yunfiqoon",
            "Who believe in the unseen, establish prayer, and spend out of what We have provided for them,",
            "جو غیب پر ایمان لاتے اور آداب کے ساتھ نماز پڑھتے اور جو کچھ ہم نے ان کو عطا فرمایا ہے اس میں سے خرچ کرتے ہیں"),
        AyahText(2, 11, 4, 1, 2, 1,
            "وَٱلَّذِينَ يُؤْمِنُونَ بِمَآ أُنزِلَ إِلَيْكَ وَمَآ أُنزِلَ مِن قَبْلِكَ وَبِٱلْءَاخِرَةِ هُمْ يُوقِنُونَ",
            "Wallazeena yu'minoona bimaa unzila ilaika wa maaa unzila min qablika wa bil Aakhirati hum yooqinoon",
            "And who believe in what has been revealed to you, [O Muhammad], and what was revealed before you, and of the Hereafter they are certain [in faith].",
            "اور جو کتاب (اے محمدﷺ) تم پر نازل ہوئی اور جو کتابیں تم سے پہلے (پیغمبروں پر) نازل ہوئیں سب پر ایمان لاتے اور آخرت کا یقین رکھتے ہیں"),
        AyahText(2, 12, 5, 1, 2, 1,
            "أُو۟لَٰٓئِكَ عَلَىٰ هُدًۭى مِّن رَّبِّهِمْ ۖ وَأُو۟لَٰٓئِكَ هُمُ ٱلْمُفْلِحُونَ",
            "Ulaaa'ika 'alaa hudam mir rabbihim wa ulaaa'ika humul muflihoon",
            "Those are upon [right] guidance from their Lord, and it is those who are the successful.",
            "یہی لوگ اپنے پروردگار (کی طرف) سے ہدایت پر ہیں اور یہی نجات پانے والے ہیں"),
        AyahText(2, 13, 6, 1, 3, 1,
            "إِنَّ ٱلَّذِينَ كَفَرُوا۟ سَوَآءٌ عَلَيْهِمْ ءَأَنذَرْتَهُمْ أَمْ لَمْ تُنذِرْهُمْ لَا يُؤْمِنُونَ",
            "Innal lazeena kafaroo sawaaa'un 'alaihim 'a-anzar tahum am lam tunzirhum laa yu'minoon",
            "Indeed, those who disbelieve - it is all the same for them whether you warn them or do not warn them - they will not believe.",
            "جو لوگ کافر ہیں انہیں تم نصیحت کرو یا نہ کرو ان کے لیے برابر ہے۔ وہ ایمان نہیں لانے کے"),
        AyahText(2, 14, 7, 1, 3, 1,
            "خَتَمَ ٱللَّهُ عَلَىٰ قُلُوبِهِمْ وَعَلَىٰ سَمْعِهِمْ ۖ وَعَلَىٰٓ أَبْصَٰرِهِمْ غِشَٰوَةٌۭ ۖ وَلَهُمْ عَذَابٌ عَظِيمٌۭ",
            "Khatamal laahu 'alaa quloobihim wa 'alaa sam'i-him wa 'alaaa absaarihim ghishaa watunw wa lahum 'azaabun 'azeem",
            "Allah has set a seal upon their hearts and upon their hearing, and over their vision is a veil. And for them is a great punishment.",
            "خدا نے ان کے دلوں اور کانوں پر مہر لگا رکھی ہے اور ان کی آنکھوں پر پردہ (پڑا ہوا) ہے اور ان کے لیے بڑا عذاب (تیار) ہے"),
        AyahText(2, 15, 8, 1, 3, 1,
            "وَمِنَ ٱلنَّاسِ مَن يَقُولُ ءَامَنَّا بِٱللَّهِ وَبِٱلْيَوْمِ ٱلْءَاخِرِ وَمَا هُم بِمُؤْمِنِينَ",
            "Wa minan naasi mai yaqoolu aamannaa billaahi wa bil yawmil aakhiri wa maa hum bimu'mineen",
            "And of the people are some who say, \"We believe in Allah and the Last Day,\" but they are not believers.",
            "اور بعض لوگ ایسے ہیں جو کہتے ہیں کہ ہم خدا پر اور روزِ آخرت پر ایمان رکھتے ہیں حالانکہ وہ ایمان نہیں رکھتے"),
        AyahText(9, 1236, 1, 10, 187, 75,
            "بَرَآءَةٌۭ مِّنَ ٱللَّهِ وَرَسُولِهِۦٓ إِلَى ٱلَّذِينَ عَٰهَدتُّم مِّنَ ٱلْمُشْرِكِينَ",
            "Baraaa'atum minal laahi wa Rasooliheee ilal lazeena 'anhattum minal mushrikeen",
            "[This is a declaration of] disassociation, from Allah and His Messenger, to those with whom you had made a treaty among the polytheists.",
            "(اے اہل اسلام اب) خدا اور اس کے رسول کی طرف سے مشرکوں سے جن سے تم نے عہد کر رکھا تھا بیزاری (اور جنگ کی تیاری) ہے"),
        AyahText(9, 1237, 2, 10, 187, 75,
            "فَسِيحُوا۟ فِى ٱلْأَرْضِ أَرْبَعَةَ أَشْهُرٍۢ وَٱعْلَمُوٓا۟ أَنَّكُمْ غَيْرُ مُعْجِزِى ٱللَّهِ ۙ وَأَنَّ ٱللَّهَ مُخْزِى ٱلْكَٰفِرِينَ",
            "Faseehoo fil ardi arba'ata ashhurinw wa'lamoooannakum ghairu mu'jizil laahi wa annal laaha mukhzil kaafireen",
            "So travel freely, [O disbelievers], throughout the land [during] four months but know that you cannot cause failure to Allah and that Allah will disgrace the disbelievers.",
            "تو (مشرکو تم) زمین میں چار مہینے چل پھر لو اور جان رکھو کہ تم خدا کو عاجز نہ کرسکو گے۔ اور یہ بھی کہ خدا کافروں کو رسوا کرنے والا ہے"),
        AyahText(18, 2141, 1, 15, 293, 117,
            "ٱلْحَمْدُ لِلَّهِ ٱلَّذِىٓ أَنزَلَ عَلَىٰ عَبْدِهِ ٱلْكِتَٰبَ وَلَمْ يَجْعَل لَّهُۥ عِوَجَا ۜ",
            "Alhamdu lillaahil lazeee anzala 'alaa 'abdihil kitaaba wa lam yaj'al lahoo 'iwajaa",
            "[All] praise is [due] to Allah, who has sent down upon His Servant the Book and has not made therein any deviance.",
            "سب تعریف خدا ہی کو ہے جس نے اپنے بندے (محمدﷺ) پر (یہ) کتاب نازل کی اور اس میں کسی طرح کی کجی (اور پیچیدگی) نہ رکھی"),
        AyahText(114, 6231, 1, 30, 604, 240,
            "قُلْ أَعُوذُ بِرَبِّ ٱلنَّاسِ",
            "Qul a'uzu birabbin naas",
            "Say, \"I seek refuge in the Lord of mankind,",
            "کہو کہ میں لوگوں کے پروردگار کی پناہ مانگتا ہوں"),
    )
}
