package com.muttaqi.android.designsystem

import androidx.annotation.DrawableRes
import com.muttaqi.android.R

@DrawableRes
fun topicSymbol(icon: String): Int = TopicSymbols[icon] ?: R.drawable.ic_menu_book

private val TopicSymbols = mapOf(
    "3dcube-linear" to R.drawable.ic_deployed_code,
    "airplane-linear" to R.drawable.ic_flight,
    "arrow-circle-down-linear" to R.drawable.ic_arrow_circle_down,
    "book-linear" to R.drawable.ic_book,
    "book-open-linear" to R.drawable.ic_menu_book,
    "briefcase-linear" to R.drawable.ic_work,
    "buildings-linear" to R.drawable.ic_apartment,
    "calendar-tick-linear" to R.drawable.ic_event_available,
    "clipboard-tick-linear" to R.drawable.ic_assignment_turned_in,
    "clock-linear" to R.drawable.ic_schedule,
    "coffee-linear" to R.drawable.ic_coffee,
    "coin-linear" to R.drawable.ic_paid,
    "courthouse-linear" to R.drawable.ic_account_balance,
    "crown-1-linear" to R.drawable.ic_crown,
    "danger-linear" to R.drawable.ic_report,
    "diamonds-linear" to R.drawable.ic_diamond,
    "document-text-linear" to R.drawable.ic_description,
    "drop-linear" to R.drawable.ic_water_drop,
    "empty-wallet-linear" to R.drawable.ic_account_balance_wallet,
    "eye-slash-linear" to R.drawable.ic_visibility_off,
    "fire-linear" to R.drawable.ic_local_fire_department,
    "flag-linear" to R.drawable.ic_flag,
    "forbidden-2-linear" to R.drawable.ic_block,
    "forbidden-linear" to R.drawable.ic_do_not_disturb_on,
    "gift-4-linear" to R.drawable.ic_redeem,
    "gift-linear" to R.drawable.ic_featured_seasonal_and_gifts,
    "happyemoji-linear" to R.drawable.ic_mood,
    "health-linear" to R.drawable.ic_health_and_safety,
    "heart-add-linear" to R.drawable.ic_heart_plus,
    "heart-circle-linear" to R.drawable.ic_favorite,
    "heart-linear" to R.drawable.ic_favorite,
    "heart-remove-linear" to R.drawable.ic_heart_minus,
    "heart-slash-linear" to R.drawable.ic_heart_broken,
    "heart-tick-linear" to R.drawable.ic_heart_check,
    "hierarchy-linear" to R.drawable.ic_account_tree,
    "hourglass-linear" to R.drawable.ic_hourglass_empty,
    "house-2-linear" to R.drawable.ic_house,
    "judge-linear" to R.drawable.ic_gavel,
    "lamp-on-linear" to R.drawable.ic_lightbulb,
    "lamp-slash-linear" to R.drawable.ic_light_off,
    "lantern-star-linear" to R.drawable.ic_nightlight,
    "layer-linear" to R.drawable.ic_layers,
    "lifebuoy-linear" to R.drawable.ic_support,
    "lock-circle-linear" to R.drawable.ic_lock,
    "lock-slash-linear" to R.drawable.ic_lock_open,
    "lovely-linear" to R.drawable.ic_volunteer_activism,
    "magic-linear" to R.drawable.ic_auto_awesome,
    "message-favorite-linear" to R.drawable.ic_reviews,
    "message-minus-linear" to R.drawable.ic_comments_disabled,
    "message-remove-linear" to R.drawable.ic_speaker_notes_off,
    "message-text-linear" to R.drawable.ic_chat,
    "messages-linear" to R.drawable.ic_forum,
    "microphone-2-linear" to R.drawable.ic_mic,
    "mirror-linear" to R.drawable.ic_self_improvement,
    "money-forbidden-linear" to R.drawable.ic_money_off,
    "money-send-linear" to R.drawable.ic_send_money,
    "moneys-linear" to R.drawable.ic_payments,
    "moon-linear" to R.drawable.ic_dark_mode,
    "people-linear" to R.drawable.ic_group,
    "percentage-circle-linear" to R.drawable.ic_percent,
    "pet-linear" to R.drawable.ic_pets,
    "profile-2user-linear" to R.drawable.ic_groups,
    "receipt-discount-linear" to R.drawable.ic_receipt_long,
    "receipt-minus-linear" to R.drawable.ic_request_quote,
    "repeat-circle-linear" to R.drawable.ic_autorenew,
    "safe-home-linear" to R.drawable.ic_cottage,
    "security-user-linear" to R.drawable.ic_admin_panel_settings,
    "serving-dome-linear" to R.drawable.ic_room_service,
    "shield-slash-linear" to R.drawable.ic_remove_moderator,
    "shield-tick-linear" to R.drawable.ic_verified_user,
    "shop-linear" to R.drawable.ic_storefront,
    "signpost-linear" to R.drawable.ic_signpost,
    "smileys-linear" to R.drawable.ic_sentiment_satisfied,
    "star-3-linear" to R.drawable.ic_star,
    "stars-linear" to R.drawable.ic_hotel_class,
    "strongbox-linear" to R.drawable.ic_inventory_2,
    "sun-fog-linear" to R.drawable.ic_wb_twilight,
    "tag-2-linear" to R.drawable.ic_sell,
    "teacher-linear" to R.drawable.ic_school,
    "timer-linear" to R.drawable.ic_timer,
    "timer-pause-linear" to R.drawable.ic_timer_pause,
    "tree-linear" to R.drawable.ic_park,
    "undo-arrow-linear" to R.drawable.ic_undo,
    "unlimited-linear" to R.drawable.ic_all_inclusive,
    "user-square-linear" to R.drawable.ic_account_box,
    "verify-linear" to R.drawable.ic_verified,
    "warning-2-linear" to R.drawable.ic_warning,
    "woman-linear" to R.drawable.ic_woman,
)
